{{ if eq .Values.cloud "aws" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.s3.credentials.name }}
        objectType: secretsmanager
        jmesPath:
          - path: S3_ACCESS_KEY_ID
            objectAlias: accessKey
          - path: S3_SECRET_ACCESS_KEY
            objectAlias: secretAccessKey
      - objectName: {{ .Values.radon.credentials.name }}
        objectType: secretsmanager
        jmesPath:
          - path: POSTGRES_PASSWORD
            objectAlias: postgres
          - path: RADON_RADON_ADMIN_PASSWORD
            objectAlias: radonAdmin
          - path: RADON_WETODB_PASSWORD
            objectAlias: wetodb
          - path: RADON_RADONCLIENT_PASSWORD
            objectAlias: radonClient
  secretObjects: # map secrets from aws secret storage to kubernetes secrets
  - data:
    - key: S3_ACCESS_KEY_ID
      objectName: accessKey
    - key: S3_SECRET_ACCESS_KEY
      objectName: secretAccessKey
    secretName: {{ .Values.s3.credentials.name }}
    type: Opaque
  - data:
    - key: POSTGRES_PASSWORD
      objectName: postgres
    - key: RADON_RADON_ADMIN_PASSWORD
      objectName: radonAdmin
    - key: RADON_WETODB_PASSWORD
      objectName: wetodb
    - key: RADON_RADONCLIENT_PASSWORD
      objectName: radonClient
    secretName: {{ .Values.radon.credentials.name }}
    type: Opaque
{{- end }}
